### ISSUE TITLE
Adding Milestones

### ISSUE THREAD

**Issue by timo-0302** [garbagemule/MobArena#464]
# Summary

* This issue is a…
    * [ ] Bug report
    * [X] Feature request
    * [ ] Documentation request
    * [ ] Other issue
    * [ ] Question
* **Describe the issue / feature in 1-2 sentences**: 

# Background

### Feature request 

* **Feature type**:
    * [ ] Arena configuration
    * [ ] Classes
    * [ ] Documentation
    * [ ] Economy integration
    * [ ] Leaderboards
    * [ ] New config settings
    * [ ] Other (please explain)
    * [X] Rewards
    * [ ] Third-party plugin support

**What does it do?**: 
Adding milestones with rewards e.g. at the first completion of wave 100 run a command that gives you the permission for a harder arena.

**Comment by garbagemule** [comment]
Why is it necessary for MobArena to keep track of this? Can't you just run the command every time the player reaches that wave? Permissions operations should be idempotent, so granting the same permission more than once should have no effect.

This is of course not possible with operations that aren't idempotent, such as adding an item to an inventory. But the example specifically mentions permissions, so if that is the only motivation, I don't see why MobArena should be weighed down by the responsibility of persistence that's already taken care of elsewhere.

**Comment by SXRWahrheit** [comment]
As a workaround, you could add a command to run a Denizen script that assigns the permission if the player doesn't have it already. You can use the same script to send text to the player, etc.
